name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Configure
      run: sudo apt-get install libgtk-3-dev libappindicator3-dev gir1.2-appindicator3-0.1
    - name: Build
      run: go build -v ./...
