name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issue_comment:
    types: [created, edited]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Configure
      run: sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev
    - name: Build
      run: go build -v ./...
